### ISSUE TITLE
Metafield edit box not loading on product page

### ISSUE THREAD

**Issue by freakdesign** [freakdesign/shopifyFD#31]
Some versions of the new admin are reporting issues with getting the metafield box to load. Looks like we'll need to adjusted the html we're pushing the mf box into.

**Comment by jameswagoner** [comment]
I have cleared cache, removed extension, tried bookmarklet and still have the error with the metafield box.

**Comment by freakdesign** [comment]
You'll need to give me more info as there's quite a few different versions of the admin in use. 
Start with some screen captures as this might narrow down which one we're talking about.

**Comment by jameswagoner** [comment]
I was digging into your commit and see you added a new selector `if(!targetHTML.length){targetHTML = $('.next-grid__cell--third:first')}` to target an prepend.

I took a look at my admin version and see the new class name for the grid. My next guess I am not getting your fix.

**Comment by jameswagoner** [comment]
So cache clearing was not enough (well via the settings in chrome). I loaded up the url to the script and a shift+F5 did it.

Versioning the file would be nice or maybe there is some other cache-buster to use with S3.

**Comment by freakdesign** [comment]
@jameswagoner The etag and expiry for the s3 files are reset on each push. Chrome just loves to hang onto that file. I don't want to start appending a cache bust url to the file as it would force a change to the script loader each time as well. Point taken however and I might shorten the expiry dates on the file in s3.

I had done a forced cdn update a few minutes before you last comment so it might have simple been down to a lack of auto update on the cdn.

**Comment by jameswagoner** [comment]
I hate cache issues all to well. Guess it is a bit tricky getting end users to update the extension or the bookmarklet.

Thanks for the awesome work. Very fast resolution to the issue as well.

**Comment by freakdesign** [comment]
No probs. Glad you're back to working. Slowly getting everybody to at least feed from the same file so it should make it easier to add in more aggressive cache busting later if need be.
