### ISSUE TITLE
ShopifyFD fails when there are querystring parameters in Product page.

### ISSUE THREAD

**Issue by yuchant** [freakdesign/shopifyFD#37]
When the Shopify Product admin appends a querystring to direct link to the "show all images" view, ShopifyFD calls fail and I have to manually remove the string / reload.

Amazing plugin. Thank you.

To reproduce: go to a product edit page, add ?foo=bar to the end of it, then try to use the delete images button.

I am using the latest Chrome store download as of August 18th on OSX.

**Comment by freakdesign** [comment]
Fixed in https://github.com/freakdesign/shopifyFD/commit/8e8135ef602f487d85b3e4d56509e13658181a99
