### ISSUE TITLE
ShopifyFD error : setup_pages : Metafield target HTML not found

### ISSUE THREAD

**Issue by chays77** [freakdesign/shopifyFD#38]
I'm using the chrome extension and everything was working perfectly after the install yesterday.

I was attempting to add metafield info for noindex nofollow on specific pages, not products in shopify.

Now today when I login I get the following error when shopifyfd is loaded.
ShopifyFD error : setup_pages : Metafield target HTML not found

The metafield editor works on products but not on pages.

**Comment by freakdesign** [comment]
This is a known problem due to a recent update to the admin interface. I've got a fix prepped and hope to push that out today. Thanks for the confirmation!

**Comment by chays77** [comment]
Awesome thank you!

**Comment by freakdesign** [comment]
FYI: This issue is fixed though the patch is yet to be pushed to github. The bookmarklets and extensions are working aok.

Consider this issue closed, but I'll mark it as so when I commit the new code here.

**Comment by DanielHirunrusme** [comment]
Hi, I'm using the Chrome extension but the error:
"ShopifyFD error : setup_pages : Metafield target HTML not found"

Is appearing when I try to load the extension on a page. It seems to work fine on the product pages. Seeing as the last commit was 15 days ago, strange there would be another conflict, but possible?

Cheers

**Comment by konung** [comment]
@freakdesign @DanielHirunrusme - confirming exactly the same issue. Just started happening today.

**Comment by freakdesign** [comment]
Thanks for the report @DanielHirunrusme and @konung. Although unusual, this was a result of a page layout change in the Admin. I've made the fix and will update shortly.

**Comment by DanielHirunrusme** [comment]
Great, thanks @freakdesign!

**Comment by inversiondk** [comment]
Hi guys, 
Just started experiencing this issue again today on the Products edit page. 
Has there been an update to the Shopify admin that interferes with the Chrome plugin?

**Comment by GraphicDesignElite** [comment]
Yes, today for me as well, i have this issue again with the plug in.

**Comment by allisonfoley** [comment]
Same issue here, today.

**Comment by Acen** [comment]
#60 temp fix provided here

**Comment by freakdesign** [comment]
If you've not already noticed this issue should be resolved in https://github.com/freakdesign/shopifyFD/issues/60.

Since the reason for the error can vary at times please make a **new** issue next time. That will make it easier for others to find via open issues.
