### ISSUE TITLE
"Remove all images" button disappears

### ISSUE THREAD

**Issue by mroncetwice** [freakdesign/shopifyFD#39]
As the title states, said button disappears upon click of the "show all images" link on the product edit screen. I'm guessing the button just needs to be re-inserted after the new HTML loads in that section.

On a side note, it'd be great to have a feature that allows for selective "multi-delete" of images in addition to the "delete all" option.

Cheers.

**Comment by freakdesign** [comment]
Looks like that section is rebuilt with ajax when clicking that button, so yes - the button is being purged. Will looking into a simple method to get around this one. Thanks for the heads up ;)

**Comment by mroncetwice** [comment]
Yea, I figured that was the case ;)

**Comment by freakdesign** [comment]
Fixed in https://github.com/freakdesign/shopifyFD/commit/8e8135ef602f487d85b3e4d56509e13658181a99
