### ISSUE TITLE
Fields don't seem to be updating on product edit

### ISSUE THREAD

**Issue by sarahtebo** [freakdesign/shopifyFD#40]
We're using the plugin to support a product size chart. If we make a mistake in entering a field -- for example, spelling a key wrong -- and then go back later to fix it, the changes don't seem to be taking effect on the front end.

Example: Accidentally ended up with the field Sizes.Mediu instead of Sizes.Medium. I removed the incorrect one and added the correct spelling. I use an if statement to check if Sizes.Medium exists, but even when doing something like: 

```
<ul>
   {% for field in product.metafields.sizes %}
   <li>{{ field | first }}: {{ field | last }}</li>
   {% endfor %}
</ul>
```

The medium sizes are still not showing up.

**Comment by freakdesign** [comment]
This could just be a typo but I see in your issue you've noted the namespace of `Sizes` as opposed to `sizes` seen in the Liquid. You might want to double check that.

Do you see the correct metafield showing when the product page is reloaded and the extension re-run? If so, that would mean the metafield is saved correctly so the tool is working as expected. As for why it doesn't show in Liquid - that would be unrelated.

Any chance of seeing an example of this in action.

**Comment by sarahtebo** [comment]
Thank you for your quick reply. You were right about the capitalization; at some point we started capitalizing the key instead of lowercase, which the liquid templates were using. I'll make sure everyone is being consistent from now on!
