### ISSUE TITLE
Meta-fields not accessable when blog is not published

### ISSUE THREAD

**Issue by Spittal** [freakdesign/shopifyFD#41]
I doesn't seem like the metafields are working when I create a blog and keep it hidden. I've testing this a few times to make sure this is reproducible bug. The steps I followed:

1. Create a new blog post.
2. Give it a name and some dummy content.
3. Save the blogpost (keeping the status hidden).
4. Load ShopifyFD (if not already loaded) and add a metatag (with any namespace, key and value)
5. Preview the blog post (while it's still hidden)

If you do this you will see the meta tags do not actually print out in the template. This feature would be nice so that we can test content before publishing a post.

Thanks.

**Comment by freakdesign** [comment]
If you've confirmed that ShopifyFD has saved the metafield correctly there's nothing it can do to force it to be included in the liquid. This is an issue with how Shopify is delivering the Metafields on unpublished posts. I've seen this before, but I'd be calling it a Shopify bug.

**Comment by freakdesign** [comment]
I've tested this and concluded that it's related to how Shopify handles the metafields for unpublished posts. I'm closing this issue.
