### ISSUE TITLE
Not able to load settings on Settings > General page

### ISSUE THREAD

**Issue by HandHugs** [freakdesign/shopifyFD#42]
Not sure what happened, but I am unable to load the settings section on my Settings > General page where they normally are. I load both the ShopifyFD tool, and the Custom metafields tool (chrome extensions) and they appear to have loaded (i get the bar across the top, and the pink notice on the sidebar), but there is no longer a place for me to edit / add new metafields to the site. I can do it from a product page, but would like the option to do it from the Settings page again. Any advice? I tried quitting chrome and re-opening it as well (no effect).

**Comment by freakdesign** [comment]
I can replicate this issue. Thank you for submitting it!

A new update to the html in the settings > general page so the ShopifyFD is unsure of where to to put the metafield box. For safety it opts to not sure anything to avoid breaking the admin. 

I'll get a fixed pushed for this shortly so it works with the new layout.

**Comment by freakdesign** [comment]
A fix has been made so I'll upload that now. Be prepared to clear browser cache.

Do note that the fix isn't very pretty, but should at least let you edit those metafields. I'll adjust the layout after xmas ;)
