### ISSUE TITLE
Show SKUs & ID - can be show an infinite number of times

### ISSUE THREAD

**Issue by MicrobrewMedia** [freakdesign/shopifyFD#43]
On the Product MyStoreDomain.com/admin/products page,
Instead of being able to click Show SKUs & ID multiple times and having it just replicate the SKU / ID, could we toggle the Shown/Hidden state?

**Comment by freakdesign** [comment]
Well you could just avoid clicking it twice ;)

Fair point though. I would guess there's a few buttons like this that haven't accounted for multiple clicks. I'll mark this as an enhancement (though it's kind of a bug too). I'll aim to fix it on the new release.

**Comment by freakdesign** [comment]
This still won't toggle the SKUs / IDs but the button is prevented. Once muti-page support is added I'll make a toggle.
