### ISSUE TITLE
Error: Could not add bulk redirect panel

### ISSUE THREAD

**Issue by andyhoman** [freakdesign/shopifyFD#44]
Hey Jason, just thought I'd let you know it looks like the bulk redirect panel is failing to load. May be due to the recent admin panel changes. Anyway just a heads up.

**Comment by freakdesign** [comment]
Hey Andy,

Is there any errors shown when you find the panel not loading? I did a quick (single browser) test here and I could see the redirect panel aok:
![image](https://cloud.githubusercontent.com/assets/1378665/12107318/f09949aa-b3b4-11e5-9e9b-7c8cb7db5360.png)

As a side note it looks like I've got a minor typo in the instructions so I'm going to fix up right now. It should not be `/old-url,pages/new-url` but rather `/old-url,/pages/new-url`

**Comment by andyhoman** [comment]
Hrm that's odd. Yep, I'm getting the following error when I try load FD on the /admin/redirects page.

![screengrab]
(https://s3.amazonaws.com/f.cl.ly/items/221S380D1M1x3G3w093A/Image%202016-01-05%20at%203.18.06%20PM.png)

I tried using the bookmarklet as well as the Chrome extension.

**Comment by freakdesign** [comment]
Testing (and thanks to @andyhoman) shows this can happen when the store does not have *any* redirects in place. The DOM insertion point is missing when there is no existing redirects. 

Totally a bug that needs squishing.

**Comment by andyhoman** [comment]
Hey Jason, this may or may not be related to the above or the subsequent fix but it appears that bulk URL redirects are no longer working again — at least not for me — though it's entirely likely I'm "not doing it right". 

When attempting to add a new simple one line redirect (/about-us, pages/about-us) nothing displays in the activity log and I get the following errors:

![screengrab]
(https://s3.amazonaws.com/f.cl.ly/items/0M2Q242w032i3i0u1y0Z/Image%202016-05-10%20at%2010.12.09%20PM.png?v=5825a286)

**Comment by andyhoman** [comment]
Just to follow up on this I'm thinking it has to do with the same cross domain issues that are preventing [this](http://flanneljesus.github.io/2015-05-17/shopify-301-bookmarklet/#comment-2349523600) from working too? 

FYI I manage to get the above solution to work for me by using the solution outlined in the comments.

**Comment by freakdesign** [comment]
Hey @andyhoman - thanks for the issue report. Let me dig into it and make sure it's not a bug introduced in the last update.

**Comment by freakdesign** [comment]
An update has been made to the code to better handle the url string. This structure used in the example (within the tool) is incorrect. `/about-us,'pages/about-us` should be `/about-us,/pages/about-us`. I've added some basic checks to add to preceding slash if needed, along with some whitespace trimming.

All tests checked out here, but we can open this one again if needed.
