### ISSUE TITLE
Store Metafields is not showing in Settings > General

### ISSUE THREAD

**Issue by rcanu** [freakdesign/shopifyFD#46]
The Chrome Extension is already activated however I can't see the Store Metafields still in Settings > General

**Comment by freakdesign** [comment]
To start the troubleshooting process I'm going to need a bit more info. 
- Screen capture showing that general settings page with ShopifyFD running. Make sure you hide (cover over, blur - whatever) any personal info that may show.
- Confirm that you have cleared your browser cache
- Make note of any error that you may be shown.

**Comment by freakdesign** [comment]
Since there's been no more reports on this I am going to close this issue. Will reopen as needed.
