### ISSUE TITLE
ShopifyFD error : setup_custom_collections : target html not found

### ISSUE THREAD

**Issue by MalikDrako** [freakdesign/shopifyFD#48]
I am using the Chrome extension, and everything has been working perfectly until yesterday.
I now get "ShopifyFD error : setup_custom_collections : target html not found" when trying to edit collections. Products work fine.
I assume there was an update to the admin interface that broke something.

**Comment by freakdesign** [comment]
Thanks for the heads up @MalikDrako. I can confirm this issue so I'll push out a fix shortly.
