### ISSUE TITLE
ShopifyFD error : setup_blogs : target html not found

### ISSUE THREAD

**Issue by ohneir** [freakdesign/shopifyFD#49]
When trying to edit meta fields on a Blog (not Article) I am getting an error "ShopifyFD error : setup_blogs : target html not found" 

I am using the Chrome extension. This is possibly related to issue #48 that was recently resolved?

**Comment by freakdesign** [comment]
Thanks for issue report @ohneir ;)
I can confirm this one as well so I'll get a fix prepped shortly.
