### ISSUE TITLE
Can't Pasting Shipping Rates

### ISSUE THREAD

**Issue by MicrobrewMedia** [freakdesign/shopifyFD#50]
Both the Chrome Plugin + Bookmarklet seem to copy Shipping Rates fine, but Paste does not become available after copying.

**Comment by freakdesign** [comment]
@MicrobrewMedia Thanks for the issue report. I took a (really) quick look at this and paste did appear after choosing copy. 

![image](https://cloud.githubusercontent.com/assets/1378665/13480135/92330e28-e127-11e5-8dd5-c510dcc3398e.png)

Would you mind shooting over some extra details on browser version and perhaps a screenshot of what you're seeing?

**Comment by MicrobrewMedia** [comment]
Jason, 

Glad to help. Hopefully soon I'll be able to assist other than just finding an issue... 

Setup is as follows
Mac OSX 10.10.5
Google Chrome Version 48.0.2564.116 (64-bit)
ShopifyFD Dashboard Tool 0.0.6 according to Chrome Extension Manager

Here's what's happening from a visual aspect. 
1. Hit Copy
2. Notification appears at bottom, Counts down from 6 Rates to 2. Stalls for a second and then disappears. 
3. Paste is Greyed out and Copy has turned into a Spinning "Loading" icon.
![image](https://cloud.githubusercontent.com/assets/2577265/13502481/f8dfc8da-e11f-11e5-9561-2a0d49b8aa5b.png)

**Comment by freakdesign** [comment]
Going to mark this one as a bug. Failing part way through the copy would mean that it's breaking whilst building up the list of rates. Likely a conflict with the type of rate. I'll dig into this a bit more.

**Comment by freakdesign** [comment]
I've narrowed this down to a (rather obvious) cause - being that carrier based rates work totally differently from the normal weight and price based. For now I'll add a check so that those rates are skipped in the copy, but will add a enhancement issue to include them.

**Comment by MicrobrewMedia** [comment]
Nice work man!
