### ISSUE TITLE
ShopifyFD 'select or create a metafield' dropdown doesn't show all my metafields

### ISSUE THREAD

**Issue by julbr** [freakdesign/shopifyFD#54]
First of all, amazing job with ShopifyFD!
I have over 50 metafields, and the dropdown doesn't show them all... (it shows ~40 options).
Any suggestions on how to select the metafields that don't show in the dropdown to edit or delete them?

Thanks!

**Comment by freakdesign** [comment]
I'm going to need some more info here @julbr on what metafields are not showing. Is there a common trend between the namespace or key used for this missing ones?

The tool does hide some metafields (like the seo title and description) so perhaps that blacklist is capturing the others. With more details on the metafields in place I'll be able to investigate this further.

**Comment by julbr** [comment]
Actually this seems to have fixed itself. Maybe a Chrome-related issue. I can see all my metafields in that dropdown now. Thanks!
