### ISSUE TITLE
Bulk metafields only for checked products

### ISSUE THREAD

**Issue by dexcell** [freakdesign/shopifyFD#56]
Hello,

Is there any possibility to update only check checked products metafield from products list page?

Thank you

**Comment by freakdesign** [comment]
Not something ShopifyFD does at the moment - no. The bulk editing component of ShopifyFD is very basic, but open to feedback and suggestions here.
 
The Shopify admin bulk editor does have some [metafield editing capability ](**url**) which might help too. I do have a tool in the works to make showing / hiding the metafield on the bulk editing page easier, but once you know the url format it's pretty easy to craft.

**Comment by dexcell** [comment]
Thanks! Yeah, i just noticed that shopify admin bulk editor already support metafield editing :beer: 
It's just no interface shown on the editor.

But i do hope some simple interface helper on shopifyfd to show these stuff just as future feature request. (So we don't have to remember that query string stuff format).
