### ISSUE TITLE
Meta field sorting

### ISSUE THREAD

**Issue by jack0204** [freakdesign/shopifyFD#58]
Hi,

Why the meta fields automatically sorted alphabetically in same name-space.

Like I have added the field in this order under "producttab" (namespace) and key's are 
1) All of the good stuff
2) None of the Bad Stuff
3) Ingredients

Now when I run this code 
<ul>
   {% for field in product.metafields.producttab %}
   <li>{{ field | first }}: {{ field | last }}</li>
   {% endfor %}
</ul>

It give me output like this 
1) All of the good stuff
3) Ingredients
2) None of the Bad Stuff

Please let me know how to fix this.

Thanks

**Comment by freakdesign** [comment]
The order in which metafields are returned via Liquid has nothing to do with ShopifyFD. ShopifyFD simply uses the API to add the values, but does not control how Shopfiy returns those values.

You'll need to make sure your theme Liquid has steps in place to output the values in the whatever order you need. If you're needing help with the Liquid consider posting on the [Shopify Forums](https://ecommerce.shopify.com/forums).
