### ISSUE TITLE
Error: setup_products : Metafield target HTML not found

### ISSUE THREAD

**Issue by gitteri** [freakdesign/shopifyFD#60]
This used to work just fine but today I keep running into this error on all my product pages. I can edit metafields just fine on pages. Any Ideas?

**Comment by Acen** [comment]
Looks like Shopify changed their admin panel again for some of us.

I threw my edited version onto my development store theme assets so it can be safely loaded due to their new content load policy (cdn.shopify.com).

```javascript:(function(){var gaJs = document.createElement("script");gaJs.type = "text%2Fjavascript";gaJs.src = "https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F1203%2F1744%2Ft%2F2%2Fassets%2FshopifyFD.js%3F11942521877117607321";document.getElementsByTagName("head")[0].appendChild(gaJs);})();```

**Comment by freakdesign** [comment]
I've updated the base code to get the metafield box showing again. Looks like there'll be some minor style adjustments needed, but will cover those in a general product page update.

**Comment by gitteri** [comment]
You guys are amazing.

**Comment by ghost** [comment]
Hi there! After the recent Layout-Update it happend again. This time it states: **ShopifyFD error : setup_products : Inventory target HTML not found** - Do you intend to adjust the code again? Cheers from Germany :-)

**Comment by lukekeith** [comment]
We are having the exact same problem. Very annoying since our process relies heavily on the plugin.

**Comment by vanbergen** [comment]
We have the same problem! 

Greetz from The Netherlands

**Comment by ClintBaker** [comment]
Also experiencing this issue

**Comment by henriflouquet** [comment]
Also experiencing the issue

**Comment by dmikevin** [comment]
Also experiencing this issue

**Comment by rossobrown** [comment]
Also experiencing this issue

**Comment by autobender** [comment]
Hey,
I am experiencing a similiar problem to this. I am getting this message on product pages:
setup_custom_fields() : target html not found

This is on Chrome 80.0.3987.87 on Mac. Any resolution? Or work arround?
