### ISSUE TITLE
Files: Download file list button action never completes

### ISSUE THREAD

**Issue by freakdesign** [freakdesign/shopifyFD#61]
Clicking the download file list button does nothing. The script is polling pages endlessly but never resolves. Will need to investigate and fix.

**Comment by freakdesign** [comment]
Not seeing the issue but if others do, happy to re-open this.

**Comment by sarahepitts** [comment]
Seeing this issue - nothing downloads. Using chrome extension. Thanks!
![screen shot 2018-01-14 at 07 52 27](https://user-images.githubusercontent.com/34348689/34917175-0b345c9a-f900-11e7-9c19-52ba7c481b38.png)

**Comment by freakdesign** [comment]
Thanks @sarahepitts 
I can see the same result now too - pagination is causing a little issue. I'll get this fixed.
