### ISSUE TITLE
ShopifyFD Error: setup_products: Metafield target HTML not found

### ISSUE THREAD

**Issue by NaponP** [freakdesign/shopifyFD#62]
Hello, 

For some reason the namespace, key, and value fields are not appearing for me. When launching the ShopifyFD extension I receive a notification that says "ShopifyFD Error: setup_products: Metafield target HTML not found".

I heard that Shopify made some changes to admin and this was updated. I went ahead and reinstalled the extension but I still see the same issue.

Best,
Napon

**Comment by freakdesign** [comment]
@NaponP This relates to https://github.com/freakdesign/shopifyFD/issues/60 and should already be resolved. Clear your browser cache and try again.

**Comment by freakdesign** [comment]
I'm going to assume this isn't a new issue and related to #60 as noted above. If it's not, we can re-open this.
