### ISSUE TITLE
Cannot get ShopifyFD

### ISSUE THREAD

**Issue by Mikeqhu** [freakdesign/shopifyFD#63]
Just says: Error: Shopify Admin Not Found. 

I'm logged into Shopify in Chrome.

**Comment by freakdesign** [comment]
That error would show if you try and run the extension when not logged into the Admin or don't have it as the active tab/window.

Please provide a screenshot of error including the current URL. Obviously mask/cover any personal details from the image.

**Comment by freakdesign** [comment]
Closing this. Please re-open if there's more information available.

**Comment by Mikeqhu** [comment]
Sorry for the delay. Please see below.

[image: Inline image 1]



--
Mike Hu
President/CEO
TRIO Custom Clothiers
mike@triotailoring.com

**Comment by freakdesign** [comment]
Looks like github didn't like your pic - I'm not seeing one in your reply. I'll cross fingers that attempt number two works.

**Comment by Mikeqhu** [comment]
Try this.

--
Mike Hu
TRIO Customs

**Comment by freakdesign** [comment]
You're going to need to jump back to Github and upload the file there. Replying email isn't helping to add the image. Failing that send me an email with the URL you are seeing the error on and I'll attempt to replicate it from that.
