### ISSUE TITLE
Not working in Safari only

### ISSUE THREAD

**Issue by plisvb** [freakdesign/shopifyFD#64]
Getting the following error message in the console when I try to enable shopifyfd in safari.  This is new, been using shopify fd for months.

`Refused to load https://freakdesign-us.s3.amazonaws.com/shopify/shopifyFD/s/shopifyFD.min.js because it does not appear in the script-src directive of the Content Security Policy.`

**Comment by freakdesign** [comment]
The Shopify Admin no longer allows files loaded from amazon S3. There's no workaround for that specific error so I've marked this as `wontfix`. 

The workaround would be to serve the file from another source that isn't blocked. There's a link on the bottom of [this page](https://freakdesign.com.au/pages/shopifyfd) that should be a useful alternative. It's the latest version of the bookmarklet, but hosted on the Shopify CDN.
