### ISSUE TITLE
ShopifyFD error : setup_pages : Page switcher target HTML not found

### ISSUE THREAD

**Issue by Vedaaa** [freakdesign/shopifyFD#66]
Hello,

Great tool works super well with products and collection but I get this error with pages when loading shopifyFD: ShopifyFD error : setup_pages : Page switcher target HTML not found

This is what I use in product and collection liquid:
{{collection.metafields.c_f.galleria}}
{{product.metafields.c_f.view_to_scale}}

I tried the same in pages plus what my theme developer told me to try out
{% assign c_f = page.metafields.c_f %}{{ c_f['galleria'] }}

Then I tried with what I could see in the forums
https://help.shopify.com/themes/liquid/objects/metafield

Thank so much!

Have a great day.

V

**Comment by freakdesign** [comment]
The Liquid you're using doesn't have any effect on the extension itself. 
This should now be fix via https://github.com/freakdesign/shopifyFD/issues/67

The extension will be updated shortly.
