### ISSUE TITLE
Error: setup_products_list : html not found

### ISSUE THREAD

**Issue by kenray** [freakdesign/shopifyFD#67]
I'm getting this whenever I got go display a list of products while ShopifyFD is loaded. It's been happening for a week or so (if that helps), and is probably linked to changes Shopify made to their interface.

**Comment by freakdesign** [comment]
Thanks for the heads up. I can replicate the issue so will push a fix for this shortly. Keep in mind that your cache may need to be cleared. If you're using the bookmarklet, you'll need to grab the new version.
